# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mgSiWre_oxMdKNWocrHAiPZI4feYnUor
"""

Nome = input("Digite seu nome completo: ")
idade = int(input("Digite sua idade: "))
RendaMensal = int(input("Digite sua renda mensal: "))
ValorEmprestimo = int(input("Digite o valor do emprestimo desejado "))
NumeroDeParcelas = int(input("Digite o numero de parcelas de 3 a 24: "))

while(NumeroDeParcelas <3 or NumeroDeParcelas>24):
  NumeroDeParcelas = int(input("Digite o numero de parcelas entre 3 a 24: "))

def podeAprovarPessoa(idade,RendaMensal,ValorEmprestimo,NumeroDeParcelas):
  Aprovado = 0
  if idade>=18 and ValorEmprestimo<15*RendaMensal:
    Aprovado = 1
  return Aprovado

def calcularJuros(ValorEmprestimo,NumeroDeParcelas):
  Juros = 0
  if NumeroDeParcelas<= 6:
    Juros= 0.05*ValorEmprestimo
  elif NumeroDeParcelas>=7 and NumeroDeParcelas<=12:
    Juros=0.08*ValorEmprestimo
  else:
    Juros=0.1*ValorEmprestimo
  return Juros

def calcularParcelas(valorTotal,NumeroDeParcelas):
  ValorParcelas = ValorTotal/NumeroDeParcelas
  return ValorParcelas

def podeAprovarParcela(ValorParcelas):
  AprovadoParcela = 0
  if ValorParcelas>=100 and ValorParcelas<2000:
    AprovadoParcela=1
  return AprovadoParcela

Aprovado = podeAprovarPessoa(idade,RendaMensal,ValorEmprestimo,NumeroDeParcelas)
if Aprovado == 0:
  print("seu emprestimo foi negado")
else:
  Juros = int(calcularJuros(ValorEmprestimo,NumeroDeParcelas))
  ValorTotal = Juros*NumeroDeParcelas + ValorEmprestimo
  jurosTotais=Juros*NumeroDeParcelas
  ValorParcelas = int(calcularParcelas(ValorTotal,NumeroDeParcelas))
  AprovadoParcela = int(podeAprovarParcela(ValorParcelas))
  if AprovadoParcela==0:
    print("seu emprestimo foi negado")
  else:
    print(f"Valor total: {ValorTotal}")
    print(f"ValorParcela: {ValorParcelas}")
    print(f"Juros Totais: {jurosTotais}")